let heldKeys = [];
let waitingKeys = [];
let playerId;
let playerRef;
let players = {};
let playerElements = {};
let votesRef = {};
let votingCards = {};
let votingCardElements = {};
let guns = {};
let gunElements = {};
let flashlights = {};
let flashlightElements = {};
let magnifyingGlasses = {};
let magnifyingGlassElements = {};
let halos = {};
let haloElements = {};
let mySkin = "zero";
let startingX = 133;
let startingY = 18;
let startTime;
let time;
let clock;
let clockInterval;
let playerOrder = [];                              
let isDetective = false;
let isAngel = false;
let isShooter = false;
let isVoters = false;
let playerAlive = 0;
let notified = false;
let blockNextNotification = false;
let changedName = false;
let isPlayerListOpen = false;
let stage = "Lobby";

let allPlayersRef;
let allVotingCardRef;
let allGunRef;
let allFlashlightRef;
let allMagnifyingGlassRef;
let allHaloRef;
let allVotesRef;